from math import pi,tan

RES = X,Y = 1600,900
FPS = 59
HALF_WIDTH = X // 2
HALF_HEGIHT = Y // 2

#Player
PLAYER_POS = 1.5, 5
PLAYER_ANGLE = 0
PLAYER_SPEED = 0.004
PLAYER_ROT_SPEED = 0.002

#Mouse
MAX_REL = 40
MOUSE_SPEED = 0.0002
BORDER_LEFT = 50
BORDER_RIGHT = X - BORDER_LEFT 

#FOV
FOV = pi/3 #60
HALF_FOV = FOV / 2 #30
NUM_RAYS = X // 2
HALF_NUM_RAYS = NUM_RAYS // 2
ANGLE_DELTA = FOV / NUM_RAYS
MAX_DEPTH = 20
SCREEN_DIS = HALF_WIDTH / tan(HALF_FOV)
SCALE = X / NUM_RAYS

#texture
TEXTURE = 256
TEXTURE_HALF = TEXTURE // 2